-- Insert clinics data
INSERT INTO clinics (
    id,
    name,
    description,
    website,
    starting_price,
    available_states,
    services,
    insurance_accepted,
    prescription_offered,
    lab_work_included,
    consultation_fee,
    average_wait_time,
    rating,
    review_count,
    image_url,
    trustpilot_url
) VALUES 
(
    'plume',
    'Plume',
    'Plume provides gender-affirming hormone therapy through virtual visits with licensed medical providers.',
    'https://getplume.co',
    '$99/month',
    ARRAY['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 
      'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Idaho', 'Illinois', 
      'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 
      'Massachusetts', 'Michigan', 'Minnesota', 'Missouri', 'Montana', 'Nebraska', 
      'Nevada', 'New Jersey', 'New Hampshire', 'New Mexico', 'New York', 
      'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 
      'Pennsylvania', 'Rhode Island', 'South Dakota', 'Texas', 'Tennessee', 
      'Vermont', 'Virginia', 'Utah', 'Washington', 'Washington D.C.', 
      'West Virginia', 'Wisconsin', 'Wyoming'],
    ARRAY['HRT Consultations', 'Ongoing Care', 'Lab Work', 'Letter Writing'],
    true,
    true,
    true,
    'Included in membership',
    '1-2 weeks',
    4.8,
    1250,
    '/providers/plume.png',
    'https://www.trustpilot.com/review/getplume.co'
),
(
    'folx',
    'FOLX Health',
    'FOLX Health provides comprehensive virtual healthcare services including HRT, with a focus on the LGBTQ+ community.',
    'https://www.folxhealth.com',
    '$85/month',
    ARRAY['California', 'New York', 'Massachusetts', 'Washington', 'Oregon'],
    ARRAY['HRT', 'PrEP', 'Sexual Health', 'Primary Care'],
    false,
    true,
    true,
    '$89',
    '3-5 days',
    4.7,
    890,
    '/providers/folx.png',
    'https://www.trustpilot.com/review/folxhealth.com'
),
(
    'hormonemd',
    'HormoneMD',
    'HormoneMD is a digital health platform offering comprehensive hormone therapy services including TRT, BHRT, and other hormone optimization treatments.',
    'https://www.hormonemd.com',
    '$99/month',
    ARRAY['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 
      'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Idaho', 'Illinois', 
      'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 
      'Massachusetts', 'Michigan', 'Minnesota', 'Missouri', 'Montana', 'Nebraska', 
      'Nevada', 'New Jersey', 'New Hampshire', 'New Mexico', 'New York', 
      'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 
      'Pennsylvania', 'Rhode Island', 'South Dakota', 'Texas', 'Tennessee', 
      'Vermont', 'Virginia', 'Utah', 'Washington', 'Washington D.C.', 
      'West Virginia', 'Wisconsin', 'Wyoming'],
    ARRAY['TRT for Men', 'BHRT for Women', 'Semaglutide', 'Sermorelin', 
      'Metformin', 'Rapamycin', 'DHEA', 'Lab Work', 'Unlimited Consultations'],
    false,
    true,
    true,
    'Included in subscription',
    '1-2 days',
    4.9,
    2100,
    '/providers/hormonemd.png',
    'https://www.trustpilot.com/review/hormonemd.com'
); 